"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestObjetosCuOOra,
	#superclass : #PackageManifest,
	#category : #'Objetos2-CuOOra-Manifest'
}

{ #category : #'code-critics' }
ManifestObjetosCuOOra class >> ruleRBImplementedNotSentRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'Objetos2-CuOOra')) #'2021-03-29T07:35:12.349012-03:00') )
]

{ #category : #'code-critics' }
ManifestObjetosCuOOra class >> ruleRBUnclassifiedMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'Objetos2-CuOOra')) #'2021-03-29T07:35:14.697012-03:00') )
]

{ #category : #'code-critics' }
ManifestObjetosCuOOra class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'Objetos2-CuOOra')) #'2021-03-29T07:35:08.361012-03:00') )
]
